version: '3'

services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: php.Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./src/:/var/www/
    networks:
      - backend

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./src/:/var/www/
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
      - public

  mariadb:
    container_name: mariadb
    image: mariadb:lts-jammy
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - mariadbdata:/var/lib/mysql/
      - ./config/init.sql:/docker-entrypoint-initdb.d/:ro
    networks:
      - backend
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  public:
    external: false
  backend:
    external: false
    
volumes:
  mariadbdata: {}